# Generated by Django 4.2.9 on 2024-02-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_cartitems_date_added_cartitems_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Mijoz Ismi va Familiyasi')),
                ('phone', models.CharField(max_length=10, verbose_name='Mijoz Telefon Raqami')),
                ('region', models.CharField(max_length=250, verbose_name='Viloyat va Tuman')),
                ('street', models.CharField(max_length=250, verbose_name='street')),
                ('target', models.CharField(max_length=250, verbose_name="Mo'ljal")),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(max_length=100, verbose_name="To'lov turi")),
                ('payment_status', models.CharField(max_length=100, verbose_name="To'lov holati")),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=0, verbose_name='Miqdori')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Mahsulot')),
            ],
        ),
    ]
