# Generated by Django 4.2.9 on 2024-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Naqd', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Qilinmagan', max_length=100, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='Naqd', max_length=100, verbose_name="To'lov turi"),
        ),
    ]
