# Generated by Django 4.2.9 on 2024-03-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Mijoz Telefon Raqami'),
        ),
    ]
