# Generated by Django 4.2.9 on 2024-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='barcode_image',
        ),
        migrations.AddField(
            model_name='barcode',
            name='barcode_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='barcode',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
