# Generated by Django 4.2.9 on 2024-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_barcode_barcode_image_barcode_barcode_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
