# Generated by Django 4.2.9 on 2024-03-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_sold_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
