# Generated by Django 4.2.9 on 2024-02-29 13:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_deliver', models.BooleanField(default=True)),
                ('salary', models.BigIntegerField(default=0)),
                ('position', models.CharField(default='Yetkazib beruvchi', max_length=20)),
            ],
            options={
                'verbose_name': 'Deliver',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_seller', models.BooleanField(default=True)),
                ('salary', models.BigIntegerField(default=0)),
                ('position', models.CharField(default='sotuvchi', max_length=20)),
            ],
            options={
                'verbose_name': 'Seller',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WareHouseWorker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_warehouseworker', models.BooleanField(default=True)),
                ('salary', models.BigIntegerField(default=0)),
                ('position', models.CharField(default='ombor xodimi', max_length=20)),
            ],
            options={
                'verbose_name': 'Warehouse Worker',
                'verbose_name_plural': 'Warehouse Workers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
