# Generated by Django 4.2.9 on 2024-03-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expances',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
